import React, { useState } from 'react';
import { getFacultyClassSummary } from '../../services/aiCoachesService';
import { formatScore10, getPerformanceDescriptor } from '../../lib/scoring';
import { 
  GraduationCap, 
  Users, 
  AlertTriangle, 
  Download, 
  Sparkles, 
  TrendingUp, 
  BookOpen, 
  CheckCircle2, 
  BarChart3, 
  Award, 
  ArrowRight 
} from 'lucide-react';

export const FacultyAIDashboard: React.FC = () => {
  const summary = getFacultyClassSummary();
  const [selectedBranch, setSelectedBranch] = useState<string>('All Branches');

  const branches = ['All Branches', 'CSE', 'ECE', 'EEE', 'MECH', 'CIVIL', 'AI&ML', 'DATA SCIENCE'];

  const handleExportReport = () => {
    const reportText = `SRIT COMMUNICATIVE ENGLISH LABORATORY (SAILL)
FACULTY AI CLASS PERFORMANCE & REMEDIATION REPORT
Batch: ${summary.batch}
Total Students Enrolled: ${summary.totalStudents} | Active This Week: ${summary.activeThisWeek}
At-Risk Students Count: ${summary.atRiskStudentsCount}

AVERAGE PROFICIENCY SCORES BY AI COACH (10 MARKS EVALUATION SCALE):
${Object.entries(summary.averageScoresByCoach).map(([k, v]) => `- ${k.toUpperCase()}: ${formatScore10(v)} (${getPerformanceDescriptor(v)})`).join('\n')}

COMMON LEARNING PATTERNS & FREQUENT ERRORS:
${summary.commonLearningPatterns.map((p, i) => `${i + 1}. [${p.skill}] ${p.patternTitle} (${p.frequencyPercent}% Frequency)\n   Description: ${p.description}\n   Remediation: ${p.remediationStrategy}`).join('\n\n')}

FACULTY REMEDIATION PLAN:
${summary.remediationPlanSummary}

Generated by SAILL AI Learning Engine on ${new Date().toLocaleDateString()}.`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SRIT_SAILL_Faculty_AI_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="space-y-6 text-[#2C3E50]">
      
      {/* Faculty Header */}
      <div className="srit-card p-6 bg-white border border-[#FAD7A0] flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <span className="text-[10px] font-black uppercase text-white bg-[#D35400] px-2.5 py-0.5 rounded shadow-2xs">
            SRIT Faculty Portal • R26 Syllabus
          </span>
          <h2 className="text-2xl font-extrabold text-[#2C3E50] font-heading flex items-center gap-2">
            <GraduationCap className="w-6 h-6 text-[#D35400]" />
            <span>Faculty AI Analytics & Class Learning Patterns</span>
          </h2>
          <p className="text-xs text-[#5D6D7E]">
            {summary.batch} — AI diagnostic analytics summarizing student progress and common errors.
          </p>
        </div>

        <button
          onClick={handleExportReport}
          className="px-4 py-2.5 bg-[#D35400] hover:bg-[#E67E22] text-white font-extrabold text-xs rounded-xl transition flex items-center gap-2 shadow-md shrink-0"
        >
          <Download className="w-4 h-4" />
          <span>Export Class AI Analytics Report</span>
        </button>
      </div>

      {/* Overview Stat Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        
        <div className="p-4 rounded-2xl bg-white border border-[#FAD7A0] space-y-1">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-[#5D6D7E]">Total Class Size</span>
            <Users className="w-4 h-4 text-[#D35400]" />
          </div>
          <span className="text-2xl font-black text-[#2C3E50] font-heading">{summary.totalStudents}</span>
          <span className="text-[10px] text-emerald-600 font-bold block">{summary.activeThisWeek} Active Students This Week</span>
        </div>

        <div className="p-4 rounded-2xl bg-white border border-[#FAD7A0] space-y-1">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-[#5D6D7E]">Top Performing Skill</span>
            <Award className="w-4 h-4 text-emerald-600" />
          </div>
          <span className="text-sm font-black text-[#D35400] font-heading line-clamp-1">{summary.topPerformingSkill}</span>
          <span className="text-[10px] text-[#5D6D7E] block">9 / 10 Average Proficiency (Excellent)</span>
        </div>

        <div className="p-4 rounded-2xl bg-white border border-[#FAD7A0] space-y-1">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-[#5D6D7E]">At-Risk Students</span>
            <AlertTriangle className="w-4 h-4 text-amber-600" />
          </div>
          <span className="text-2xl font-black text-amber-600 font-heading">{summary.atRiskStudentsCount}</span>
          <span className="text-[10px] text-amber-700 font-bold block">Requires Remediation Practice</span>
        </div>

        <div className="p-4 rounded-2xl bg-[#FFF8F0] border border-[#FAD7A0] space-y-1">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-[#D35400]">Overall Class Average</span>
            <TrendingUp className="w-4 h-4 text-[#D35400]" />
          </div>
          <span className="text-2xl font-black text-[#D35400] font-heading">8 / 10</span>
          <span className="text-[10px] text-[#E67E22] font-bold block">Very Good • R26 Benchmark Exceeded</span>
        </div>

      </div>

      {/* Branch Selector Filter */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
        <span className="text-xs font-bold text-[#D35400] uppercase shrink-0">Filter Branch:</span>
        {branches.map((b) => (
          <button
            key={b}
            onClick={() => setSelectedBranch(b)}
            className={`px-3 py-1 rounded-lg text-xs font-bold transition whitespace-nowrap ${
              selectedBranch === b
                ? 'bg-[#D35400] text-white shadow-2xs'
                : 'bg-white text-[#2C3E50] border border-[#FAD7A0] hover:bg-[#FFF8F0]'
            }`}
          >
            {b}
          </button>
        ))}
      </div>

      {/* Common Learning Patterns & Frequent Errors Section */}
      <div className="srit-card p-6 bg-white border border-[#FAD7A0] space-y-4">
        <div className="border-b border-[#FAD7A0] pb-3">
          <h3 className="text-base font-extrabold text-[#D35400] font-heading flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-[#D35400]" />
            <span>Common Learning Patterns & Frequent Diagnostic Errors</span>
          </h3>
          <p className="text-xs text-[#5D6D7E]">Aggregated AI error analysis across student submissions</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {summary.commonLearningPatterns.map((pattern, idx) => (
            <div key={idx} className="p-4 rounded-2xl bg-[#FFF8F0] border border-[#FAD7A0] space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-extrabold text-white bg-[#D35400] px-2 py-0.5 rounded">
                  {pattern.skill}
                </span>
                <span className="text-xs font-black text-amber-700 font-heading">
                  {pattern.frequencyPercent}% Frequency
                </span>
              </div>

              <h4 className="text-xs font-extrabold text-[#2C3E50]">{pattern.patternTitle}</h4>
              <p className="text-xs text-[#5D6D7E] leading-relaxed">{pattern.description}</p>

              <div className="p-3 bg-white border border-[#FAD7A0] rounded-xl space-y-1">
                <span className="text-[10px] font-bold text-[#E67E22] uppercase block">Faculty Action Item:</span>
                <p className="text-xs text-[#2C3E50] font-medium">{pattern.remediationStrategy}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* AI Class Remediation Plan Summary */}
      <div className="p-5 rounded-2xl bg-[#FFF8F0] border-2 border-[#FAD7A0] space-y-3">
        <h3 className="text-base font-extrabold text-[#D35400] font-heading flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-[#D35400]" />
          <span>SRIT Faculty AI Remediation Strategy</span>
        </h3>
        <p className="text-xs text-[#2C3E50] leading-relaxed font-medium">
          {summary.remediationPlanSummary}
        </p>
      </div>

    </div>
  );
};
